workflow "Depkoy Worker {
  on = "push"
  resolves = ["cloudflare/serverless-action@master"]
}

action "Deploy Worker" {
  uses = "cloudflare/serverless-action@master"
  env = {
    CLOUDFLARE_ACCOUNT_ID = "ACCOUNT_ID"
    CF_API_TOKEN = "CF_API_TOKEN"
  }
  secrets = [CLOUDFLARE_ACCOUNT_ID,"CF_API_TOKEN"]
}
